# Page config variables
page_title = 'Story Sprout: Engaging, Culturally Diverse, & Emotionally Intelligent Short Stories for Children'
menu_items = {
    'Get Help': 'mailto:danioshi@gmail.com',
    'Report a bug': "mailto:danioshi@gmail.com",
    'About': "# Made by Daniel Osorio. This app uses *OpenAI ChatGPT*."
}

# Sidebar variables
sidebar_how_to_use = """
1. Provide a short statement (prompt) to generate a short story.
2. Indicate the age of the child(ren) (the reader) to personalize your story to their age group.
3. Please wait a couple of minutes so the story gets generated by AI.
"""

openai_gpt4_url = "https://openai.com/gpt-4"

faq = (
    {
        'question': 'What is Story Sprout?',
        'answer': "Story Sprout is an app that generates personalized, respectful, and engaging short stories for "
                  "children aged 0-8 years old.",
    },
    {
        'question': "How does Story Sprout work?",
        'answer': "You input a short question or statement (prompt) that guides your story creation. You can think of "
                  "it as the seed from which your unique story will grow. Then our advanced AI creates a unique "
                  "story based on your inputs.",
    },
    {
        'question': "What kind of stories does Story Sprout create?",
        'answer': "Story Sprout crafts stories that are grounded in everyday experiences, respect diversity, promote "
                  "non-violence, and foster emotional intelligence. We create stories that respect children's "
                  "feelings, emotions, and autonomy.",
    },
    {
        'question': "What are some examples of short statements I could use?",
        'answer': """
            "Emma and her best friend Bella decide to start a band." 
            "A story about a sunny day at the beach where Charlie learns to build a sandcastle."  
            "Oliver goes on an adventure in his backyard."
            """,
    },
    {
        'question': "How long does it take to create a story?",
        'answer': "After you input short statement, our AI needs a few moments to craft your story. "
                  "So sit back, relax, and let Story Sprout do its magic!",
    },
    {
        'question': "Can I influence the content of the story?",
        'answer': "Yes, you guide the story by providing an initial short statement and indicating the age of the "
                  "reader(s). "
                  "For example, you can input their favorite color, food, or themes like animals or music.",
    },
    {
        'question': "Will all the stories be different?",
        'answer': "Yes, each story generated by Story Sprout is unique, thanks to the input you provide and the "
                  "advanced AI that crafts the story. Even when using similar short statements or preferences, "
                  "the AI is designed to create different narratives, ensuring a fresh and engaging experience "
                  "each time.",
    },
    {
        'question': "Can I share the stories that Story Sprout generates?",
        'answer': "Absolutely! You can share your unique Story Sprout creations with family and friends.",
    },
    {
        'question': "Can I request a story with specific themes or lessons?",
        'answer': "While Story Sprout is designed to create narratives that reflect everyday situations and do not "
                  "explicitly convey a moral or lesson, you can certainly guide the theme of the story with your "
                  "input. However, keep in mind the goal is to depict respectful, real-world situations, "
                  "not to moralize.",
    },
    {
        'question': "Is Story Sprout suitable for children with special needs?",
        'answer': "Story Sprout aims to be inclusive and respectful. You can customize the story to suit your child's "
                  "preferences and needs. However, as every child is unique, the suitability might depend on "
                  "specific needs and contexts.",
    },
    {
        'question': "What kind of personal data do I need to share with Story Sprout?",
        'answer': "Nothing really. You only need to provide the preferences and inputs that you're comfortable with. "
                  "Story Sprout doesn't require detailed personal information to generate stories. We respect your "
                  "privacy and the safety of your data.",
    },
    {
        'question': "Is Story Sprout safe for my child to use alone?",
        'answer': "While Story Sprout generates child-friendly and respectful stories, we always recommend adult "
                  "supervision when children are using digital devices. This ensures a safe and guided experience.",
    },
    {
        'question': "What do you do with my data?",
        'answer': "We will save the prompt and generated story for refining purposes. "
                  "We will also save the rating and feedback if provided. "
                  "We won't sell your data.",
    },
    {
        'question': "What AI do you use?",
        'answer': f"We use OpenAI's ChatGPT 4 <{openai_gpt4_url}> 🔗",
    },
)

# Main prompt variables
prompt_text_area_help = 'Let us know what the story should be about, indicating the name of the child(ren) involved ' \
                        'and any other detail you think is relevant to the story'
prompt_caption = '*For example: Write a story about a 6-year-old boy named Alex who accidentally ' \
                 'breaks a vase at home.*\n\n' \
                 'You can write in your favorite language too, and story sprout will produce a story ' \
                 'in your language.'
prompt_age_help = 'The age of your child (the reader) will help us tailor the story for the age group. ' \
                  'We currently support from 0 to 8 years old'
prompt_no_text_error = 'Please tell us what the story is about.\n\n' \
                       'For example: *A child named Jamie learns about different emotions ' \
                       'when they lose their favorite toy and then find it again.*'
openai_url = "https://openai.com/policies/usage-policies"
prompt_flagged_error = "Your prompt does not comply with OpenAI's " \
                       f"usage policies: <{openai_url}> 🔗.\n\n" \
                       "Please try again."
prompt_button_caption = 'Each time you click on "Generate story", a new story will be created. ' \
                        'All the stories will remain here until you refresh the page or restart the app.'

# Rate section variables
rate_options = {
    0: '0️⃣ - 😞',
    1: '1️⃣ - 🫤',
    2: '2️⃣ - 😐',
    3: '3️⃣ - 🙂',
    4: '4️⃣ - 😊',
    5: '5️⃣ - 🤩',
}
rate_msg = "Thank you for using Story Sprout! We hope you enjoyed your unique story. " \
           "We'd love to hear what you thought about it - your feedback helps us " \
           "improve and deliver even better stories. And if you have any extra " \
           "thoughts or suggestions, don't hesitate to share them with us. " \
           "Thank you for helping Story Sprout grow!"

# Support variables
example_story = """
Once upon a time, in a small, cozy house, lived a child named Sam. Sam loved playing in their big, green backyard. 
It was filled with tall trees, colorful flowers, and soft grass. Everyday after breakfast, Sam would run outside to 
explore and discover new things.

One sunny morning, while Sam was exploring the garden, they heard a soft chirp near the bushes. Sam carefully peeked 
through the leaves and found a little bird. The bird had a hurt wing and couldn't fly.

Sam's heart filled with compassion, and they gently said, "Oh no, little bird, your wing is hurt. Let me help you." 
Sam went inside the house and asked their mom for a shoebox to make the bird a comfy, safe home.

Their mom listened carefully and lovingly helped Sam prepare the shoebox with soft, clean cloth inside. "Make sure 
the bird has some water and plant-based food, like seeds or berries," she advised. Sam nodded and thanked their mom.

Sam carefully placed the little bird in the shoebox and set it in a quiet spot underneath the tree. They brought 
fresh water in a small lid and searched the garden for some seeds and ripe berries.

For several days, Sam took care of the bird in the box. They made sure the bird had enough water, seeds, and berries 
to eat, while also giving the bird space to rest and feel safe.

One morning, as Sam checked on the little bird, they noticed that its wing seemed much better. The bird looked eager 
to stretch and try to fly again. Sam gently said, "Little bird, I think you're ready to fly again. 
Let's try it outside."

With a big, excited smile, Sam carried the shoebox outside. They gently opened the box, stepped back, and softly 
whispered, "You can do it, little bird. I believe in you."

The bird stretched its wings, feeling strong and healthy again, and with a grateful chirp, it flew up, up, up 
into the sky. Sam watched as the little bird soared high and disappeared among the trees.

Sam knew they would miss the little bird, but they felt happy knowing they had helped a friend in need. From 
that day on, every time they heard a bird's melodious song, Sam would remember their sweet little 
visitor and the love they shared.
"""
